# Generated by Django 5.1.4 on 2025-01-16 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0002_rename_slug_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
    ]
