# Generated by Django 5.1.4 on 2025-02-17 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Category', '0004_category_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(default='Descripcion por defecto', max_length=250)),
                ('slug', models.SlugField(default='poner nombre del slug', max_length=200, unique=True)),
                ('views', models.IntegerField(blank=True, default=0)),
                ('price', models.FloatField(blank=True, default=0.0)),
                ('original_price', models.FloatField(blank=True, default=0.0)),
                ('image', models.ImageField(max_length=255, null=True, upload_to='products/images/')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Category.category')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='ViewCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_view_count', to='Productos.product')),
            ],
        ),
    ]
