# Generated by Django 5.1.4 on 2025-02-21 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='imagen_url',
            field=models.URLField(default='https://media.istockphoto.com/id/2189194504/es/foto/female-hand-with-manicure-holding-gold-mascara-tube.jpg?s=612x612&w=0&k=20&c=ooDe4HsRHaLyivbtjbKcXxcC14DMVo1neUNC302WOdg=', max_length=500),
        ),
    ]
