# Generated by Django 5.1.4 on 2025-02-21 15:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0002_remove_product_image_product_imagen_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='product',
            name='views',
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=5.0, max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='imagen_url',
            field=models.URLField(default='https://media.istockphoto.com/id/2189194504/es/foto/female-hand-with-manicure-holding-gold-mascara-tube.jpg?s=612x612&w=0&k=20&c=ooDe4HsRHaLyivbtjbKcXxcC14DMVo1neUNC302WOdg=', max_length=700),
        ),
    ]
