# Generated by Django 5.1.4 on 2025-02-24 15:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0003_remove_product_slug_remove_product_views_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=5.0, max_digits=2, validators=[django.core.validators.MinValueValidator('0'), django.core.validators.MaxValueValidator('5')]),
        ),
    ]
