# Generated by Django 5.1.4 on 2025-04-22 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0008_remove_product_imagen_url_product_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imagen',
            field=models.ImageField(default='products/default.png', upload_to='products/'),
        ),
    ]
