# Generated by Django 5.1.4 on 2024-12-14 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModaHombre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('price', models.FloatField(blank=True, default=0)),
                ('original_price', models.FloatField(blank=True, default=0)),
                ('image', models.ImageField(max_length=255, null=True, upload_to='moda_hombre/images/')),
                ('review_count', models.FloatField(blank=True, default=0)),
                ('freeShipping', models.BooleanField()),
                ('seller', models.JSONField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Category.category')),
            ],
            options={
                'verbose_name': 'Moda Hombre',
                'verbose_name_plural': 'Moda Hombres',
            },
        ),
        migrations.CreateModel(
            name='ViewCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_addres', models.CharField(max_length=255)),
                ('moda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modaHombre_view_count', to='Moda_Hombre.modahombre')),
            ],
        ),
    ]
