# Generated by Django 5.1.4 on 2024-12-14 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Moda_Hombre', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modahombre',
            name='seller',
        ),
    ]
