# Generated by Django 5.1.4 on 2024-12-14 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moda_Hombre', '0002_remove_modahombre_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='modahombre',
            name='views',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
