# Generated by Django 5.1.4 on 2024-12-16 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Moda_Hombre', '0003_modahombre_views'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viewcount',
            old_name='ip_addres',
            new_name='ip_address',
        ),
    ]
