# Generated by Django 5.1.4 on 2025-01-16 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0003_remove_category_parent'),
        ('Moda_Hombre', '0004_rename_ip_addres_viewcount_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modahombre',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Category.category'),
        ),
    ]
